spring.application.name=api-gateway
server.port=8080

# Forward timeout
spring.mvc.async.request-timeout=60000

# File upload max size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Downstream Microservices Ports
gateway.services.user-service=http://localhost:8081
gateway.services.inventory-service=http://localhost:8082
gateway.services.recipe-service=http://localhost:8083
gateway.services.plan-shopping-service=http://localhost:8084
gateway.services.ai-service=http://localhost:8085
gateway.services.social-stats-service=http://localhost:8086

# HTTP Compression (Gzip)
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,image/svg+xml
server.compression.min-response-size=1024

