spring.application.name=foodx-prod

# ====== Datasource (lấy từ biến môi trường) ======
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ====== JPA ======
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ====== JWT (lấy từ biến môi trường) ======
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
