-- Fix corrupted ingredients with exact Vietnamese UTF-8 text
UPDATE ingredients SET name = 'Thịt ba chỉ', default_unit = 'g', category = 'Thịt' WHERE id = 18;
UPDATE ingredients SET name = 'Thịt nạc vai xay', default_unit = 'g', category = 'Thịt' WHERE id = 19;
UPDATE ingredients SET name = 'Thịt gà ta', default_unit = 'g', category = 'Thịt' WHERE id = 20;
UPDATE ingredients SET name = 'Ức gà fillet', default_unit = 'g', category = 'Thịt' WHERE id = 21;
UPDATE ingredients SET name = 'Thịt bò thăn', default_unit = 'g', category = 'Thịt' WHERE id = 22;
UPDATE ingredients SET name = 'Bắp bò hoa', default_unit = 'g', category = 'Thịt' WHERE id = 23;
UPDATE ingredients SET name = 'Bò ba chỉ Mỹ', default_unit = 'g', category = 'Thịt' WHERE id = 24;
UPDATE ingredients SET name = 'Sườn non heo', default_unit = 'g', category = 'Thịt' WHERE id = 25;
UPDATE ingredients SET name = 'Móng giò heo', default_unit = 'g', category = 'Thịt' WHERE id = 26;
UPDATE ingredients SET name = 'Cá chẽm tươi', default_unit = 'g', category = 'Hải sản' WHERE id = 27;
UPDATE ingredients SET name = 'Phi lê cá hồi Nauy', default_unit = 'g', category = 'Hải sản' WHERE id = 28;
UPDATE ingredients SET name = 'Tôm sú tươi', default_unit = 'g', category = 'Hải sản' WHERE id = 29;
UPDATE ingredients SET name = 'Cua đồng xay', default_unit = 'g', category = 'Hải sản' WHERE id = 30;
UPDATE ingredients SET name = 'Trứng vịt', default_unit = 'quả', category = 'Trứng' WHERE id = 31;
UPDATE ingredients SET name = 'Trứng gà tươi', default_unit = 'quả', category = 'Trứng' WHERE id = 32;
UPDATE ingredients SET name = 'Đậu hũ non', default_unit = 'hộp', category = 'Đậu hạt' WHERE id = 33;
UPDATE ingredients SET name = 'Đậu xanh xát vỏ', default_unit = 'g', category = 'Đậu hạt' WHERE id = 34;
UPDATE ingredients SET name = 'Đậu nành hạt', default_unit = 'g', category = 'Đậu hạt' WHERE id = 35;
UPDATE ingredients SET name = 'Bánh phở tươi', default_unit = 'g', category = 'Tinh bột' WHERE id = 36;
UPDATE ingredients SET name = 'Bún tươi', default_unit = 'g', category = 'Tinh bột' WHERE id = 37;
UPDATE ingredients SET name = 'Bún gạo lứt', default_unit = 'g', category = 'Tinh bột' WHERE id = 38;
UPDATE ingredients SET name = 'Bánh mì giòn', default_unit = 'ổ', category = 'Tinh bột' WHERE id = 39;
UPDATE ingredients SET name = 'Gạo tấm thơm', default_unit = 'g', category = 'Tinh bột' WHERE id = 40;
UPDATE ingredients SET name = 'Gạo nếp cái hoa vàng', default_unit = 'g', category = 'Tinh bột' WHERE id = 41;
UPDATE ingredients SET name = 'Bột bánh cuốn', default_unit = 'g', category = 'Tinh bột' WHERE id = 42;
UPDATE ingredients SET name = 'Bột nếp', default_unit = 'g', category = 'Tinh bột' WHERE id = 43;
UPDATE ingredients SET name = 'Bột năng', default_unit = 'g', category = 'Tinh bột' WHERE id = 44;
UPDATE ingredients SET name = 'Yến mạch cán dẹt', default_unit = 'g', category = 'Tinh bột' WHERE id = 45;
UPDATE ingredients SET name = 'Bông cải xanh', default_unit = 'g', category = 'Rau củ' WHERE id = 46;
UPDATE ingredients SET name = 'Cà chua bi', default_unit = 'g', category = 'Rau củ' WHERE id = 47;
UPDATE ingredients SET name = 'Cần tây', default_unit = 'g', category = 'Rau củ' WHERE id = 48;
UPDATE ingredients SET name = 'Tỏi tây', default_unit = 'g', category = 'Rau củ' WHERE id = 49;
UPDATE ingredients SET name = 'Măng tây tươi', default_unit = 'g', category = 'Rau củ' WHERE id = 50;
UPDATE ingredients SET name = 'Rau mồng tơi', default_unit = 'g', category = 'Rau củ' WHERE id = 51;
UPDATE ingredients SET name = 'Rau đay', default_unit = 'g', category = 'Rau củ' WHERE id = 52;
UPDATE ingredients SET name = 'Mướp hương', default_unit = 'quả', category = 'Rau củ' WHERE id = 53;
UPDATE ingredients SET name = 'Rong biển khô', default_unit = 'g', category = 'Rau củ' WHERE id = 54;
UPDATE ingredients SET name = 'Nấm đùi gà', default_unit = 'g', category = 'Nấm' WHERE id = 55;
UPDATE ingredients SET name = 'Nấm đông cô', default_unit = 'g', category = 'Nấm' WHERE id = 56;
UPDATE ingredients SET name = 'Nấm hương mộc nhĩ', default_unit = 'g', category = 'Nấm' WHERE id = 57;
UPDATE ingredients SET name = 'Cùi bưởi da xanh', default_unit = 'g', category = 'Trái cây' WHERE id = 58;
UPDATE ingredients SET name = 'Chuối sứ chín', default_unit = 'quả', category = 'Trái cây' WHERE id = 59;
UPDATE ingredients SET name = 'Hạt sen tươi', default_unit = 'g', category = 'Hạt' WHERE id = 60;
UPDATE ingredients SET name = 'Long nhãn Hưng Yên', default_unit = 'g', category = 'Trái cây' WHERE id = 61;
UPDATE ingredients SET name = 'Nước dừa xiêm', default_unit = 'ml', category = 'Gia vị' WHERE id = 62;
UPDATE ingredients SET name = 'Nước cốt dừa', default_unit = 'ml', category = 'Gia vị' WHERE id = 63;
UPDATE ingredients SET name = 'Sữa đặc', default_unit = 'ml', category = 'Sữa' WHERE id = 64;
UPDATE ingredients SET name = 'Sữa tươi không đường', default_unit = 'ml', category = 'Sữa' WHERE id = 65;
UPDATE ingredients SET name = 'Mắm tôm ngon', default_unit = 'ml', category = 'Gia vị' WHERE id = 66;
UPDATE ingredients SET name = 'Mắm ruốc Huế', default_unit = 'g', category = 'Gia vị' WHERE id = 67;

-- Ensure all social posts have PUBLISHED status
UPDATE recipe_posts SET status = 'PUBLISHED' WHERE status IS NULL OR status = '';
